### ISSUE TITLE
Panics when combining autoApprovers

### ISSUE THREAD

**Issue by twelsh-aw** [tailscale-dev/tailscale-acl-combiner#24]
For a similar reason as #23 , we can get panics when combining files with `autoApprovers` definitions. 

Simple repro:

parent.json:
```json
{}
```

children/child1.json
```json
{
    "autoApprovers": {
        "routes": {
            "10.0.0.0/32": [
                "tag:example"
            ],
        },
        "exitNode": []
    }
}
```

children/child2.json
```json
{
    "autoApprovers": {
        "routes": {
            "10.0.0.1/32": [
                "tag:example"
            ],
        },
        "exitNode": []
    }
}
```

error:
```text
tailscale-acl-combiner -v \   
  -f ./repro/parent.json \
  -d ./repro/children \
  -o ./repro/generated.hujson \
  -allow autoApprovers

parsing [./repro/parent.json]...
walking path [./repro/children]...
parsing [repro/children/child1.json]...
parsing [repro/children/child2.json]...
allowing ACL sections [map[autoApprovers:0x100e0a760]]
section [autoApprovers] not found in parent doc, creating new object
section [exitNode] not found in parent doc, creating new array
section [routes] not found in parent doc, creating new object
section [autoApprovers] found in parent doc, re-using object
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.handleArray.func1({0x10060d7e7, 0x8}, {0x16f8a7112, 0x28}, 0x14000120b40, {0x140001260f0, 0x2f}, 0x14000120900)
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:140 +0x2ac
main.init.handleAutoApprovers.func2({0x16f8a719c, 0xd}, {0x16f8a7112, 0x28}, 0x14000120090, {0x140001260f0, 0x2f}, 0x14000120630)
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:194 +0x10c
main.mergeDocs(0x140001142a0, 0x1400012e000, {0x14000122220, 0x2, 0x5?})
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:235 +0x278
main.main()
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:114 +0x2f0
```

This is because the empty `exitNode` array from the first merge gets added to parent and then on the second merge, we only do a non-nil check (and not a non-empty check) when checking parent where the panic happens.

______________________________________________________________

There is also a separate panic if the child omits `exitNode` altogether:

parent.json:
```json
{}
```

children/child.json
```json
{
    "autoApprovers": {
        "routes": {
            "10.0.0.0/32": [
                "tag:example"
            ]
        }
    }
}
```

```text
tailscale-acl-combiner -v \
  -f ./repro2/parent.json \
  -d ./repro2/children \
  -o ./repro2/generated.hujson \
  -allow autoApprovers

parsing [./repro2/parent.json]...
walking path [./repro2/children]...
parsing [repro2/children/child.json]...
allowing ACL sections [map[autoApprovers:0x104bda760]]
section [autoApprovers] not found in parent doc, creating new object
section [exitNode] not found in parent doc, creating new array
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104bda1b8]

goroutine 1 [running]:
main.handleArray.func1({0x104bdd7e7, 0x8}, {0x16b2d7115, 0x28}, 0x140000bc480, {0x140000b6090, 0x2f}, 0x0)
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:144 +0x108
main.init.handleAutoApprovers.func2({0x16b2d719f, 0xd}, {0x16b2d7115, 0x28}, 0x140000bc000, {0x140000b6090, 0x2f}, 0x140000bc090)
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:194 +0x10c
main.mergeDocs(0x1400009c240, 0x140000be000, {0x140000a4058, 0x1, 0x5?})
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:235 +0x278
main.main()
        /Users/.../go/pkg/mod/github.com/tailscale-dev/tailscale-acl-combiner@v0.0.0-20241104222340-a9d8794d80c7/main.go:114 +0x2f0
```

**Comment by clstokes** [comment]
@twelsh-aw thanks for reporting and the great repro info. Fixed!
